import Link from "next/link";
import { BellRing, Eye, EyeOff, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { cohortLabel } from "@/lib/commodities";
import { conditionLabel } from "@/lib/price-watches";
import { UNIT_RULES } from "@/lib/units";
import { countryName } from "@/lib/countries";
import { deletePriceWatchAction, setPriceWatchEnabledAction, updateEmailPriceAlertPreferenceAction, updatePriceAlertPreferenceAction } from "@/app/actions/price-watches";

export default async function PriceWatchesPage({ searchParams }: { searchParams: Promise<{ created?: string; email?: string }> }) {
  const user = await requireUser();
  const [watches, preference] = await Promise.all([
    prisma.priceWatch.findMany({ where: { userId: user.id }, orderBy: [{ createdAt: "desc" }, { id: "desc" }] }),
    prisma.notificationPreference.findUnique({ where: { userId: user.id } }),
  ]);
  const params = await searchParams;
  const created = params.created === "1";
  return <AppShell>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase text-[#47715f]">Price alerts</p><h1 className="mt-2 text-3xl font-bold">Price Watches</h1><p className="mt-3 text-sm text-[#6f626b]">Watch comparable Sauti asking-price cohorts. Alerts use recorded history, not completed sales.</p></div><Link href="/market/insights" className="inline-flex min-h-11 items-center rounded-lg bg-[#20141d] px-4 text-sm font-bold text-white">Create from Insights</Link></header>
    {created && <p className="mt-5 border border-green-200 bg-green-50 p-3 text-sm font-semibold text-green-800">Price watch created.</p>}
    <section className="mt-7 flex flex-wrap items-center justify-between gap-4 border-y border-[#eadfdf] py-5"><div><h2 className="font-bold">In-app price alerts</h2><p className="mt-1 text-sm text-[#6f626b]">Email, SMS, and push delivery are not enabled.</p></div><form action={updatePriceAlertPreferenceAction}><input type="hidden" name="enabled" value={(preference?.inAppPriceAlerts ?? true) ? "false" : "true"} /><button className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#d9cccc] bg-white px-4 text-sm font-bold">{(preference?.inAppPriceAlerts ?? true) ? <Eye size={18} /> : <EyeOff size={18} />}{(preference?.inAppPriceAlerts ?? true) ? "Enabled" : "Disabled"}</button></form></section>
    <section className="flex flex-wrap items-center justify-between gap-4 border-b border-[#eadfdf] py-5"><div><h2 className="font-bold">Email price alerts</h2><p className="mt-1 text-sm text-[#6f626b]">{user.emailVerifiedAt ? "Receive triggered price-watch alerts at your verified email address." : "Verify your email to receive price alerts."}</p>{params.email === "verify" && <p role="alert" className="mt-2 text-sm font-semibold text-[#9d334b]">Verify your email to receive price alerts.</p>}</div>{user.emailVerifiedAt ? <form action={updateEmailPriceAlertPreferenceAction}><input type="hidden" name="enabled" value={(preference?.emailPriceAlerts ?? false) ? "false" : "true"} /><button className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#d9cccc] bg-white px-4 text-sm font-bold">{(preference?.emailPriceAlerts ?? false) ? <Eye size={18} /> : <EyeOff size={18} />}{(preference?.emailPriceAlerts ?? false) ? "Enabled" : "Disabled"}</button></form> : <Link href="/profile" className="inline-flex min-h-11 items-center rounded-lg border border-[#d9cccc] bg-white px-4 text-sm font-bold">Verify email</Link>}</section>
    {watches.length ? <div className="mt-6 divide-y divide-[#eadfdf] border-y border-[#eadfdf]">{watches.map(watch => { const unit = UNIT_RULES[watch.normalizedUnit].label; return <article key={watch.id} className="py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h2 className="break-words text-lg font-bold">{cohortLabel(watch.commodity, watch.variety, watch.grade)}</h2><p className="mt-1 text-sm font-semibold text-[#47715f]">{conditionLabel(watch.condition, watch.threshold, unit)}</p><p className="mt-2 text-xs text-[#6f626b]">{watch.country ? countryName(watch.country) : "All countries"}{watch.location ? ` · ${watch.location}` : ""} · {watch.enabled ? "Enabled" : "Disabled"}</p><p className="mt-1 text-xs text-[#6f626b]">{watch.lastEvaluatedAt ? `Last evaluated ${watch.lastEvaluatedAt.toISOString().replace("T", " ").slice(0, 16)} UTC${watch.lastValue ? ` · value ${watch.lastValue.toString()}` : " · insufficient history"}` : "Not evaluated yet"}</p></div><div className="flex gap-2"><form action={setPriceWatchEnabledAction}><input type="hidden" name="id" value={watch.id} /><input type="hidden" name="enabled" value={watch.enabled ? "false" : "true"} /><button title={watch.enabled ? "Disable watch" : "Enable watch"} aria-label={watch.enabled ? "Disable watch" : "Enable watch"} className="grid size-11 place-items-center rounded-lg border border-[#d9cccc] bg-white">{watch.enabled ? <EyeOff size={18} /> : <Eye size={18} />}</button></form><form action={deletePriceWatchAction}><input type="hidden" name="id" value={watch.id} /><button title="Delete watch" aria-label="Delete watch" className="grid size-11 place-items-center rounded-lg border border-[#d9cccc] bg-white text-[#9d334b]"><Trash2 size={18} /></button></form></div></div></article>; })}</div> : <section className="mt-8 border-y border-dashed border-[#d9cccc] py-12"><BellRing size={30} className="text-[#9d334b]" /><h2 className="mt-4 text-xl font-bold">No price watches yet.</h2><p className="mt-2 text-sm text-[#6f626b]">Choose a structured cohort in Market Insights to create one.</p></section>}
  </AppShell>;
}
