import { AlertTriangle, CheckCircle2, Clock3 } from "lucide-react";
import { requireAdmin } from "@/lib/admin/auth";
import { priceWatchRunHealth } from "@/lib/admin/price-watch-runs";

export default async function EvaluationRunsPage() {
  await requireAdmin();
  const data = await priceWatchRunHealth();
  const latest = data.latest;
  return <><header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase text-[#996066]">Alert operations</p><h1 className="mt-2 text-3xl font-bold">Evaluator runs</h1><p className="mt-3 max-w-2xl text-sm text-[#6f626b]">Persistent operational records for manual and scheduled price-watch evaluation.</p></div><div className={`flex items-center gap-2 rounded-lg border px-4 py-3 text-sm font-bold ${data.status === "Healthy" ? "border-green-200 bg-green-50 text-green-800" : "border-amber-200 bg-amber-50 text-amber-900"}`}>{data.status === "Healthy" ? <CheckCircle2 size={19} /> : <AlertTriangle size={19} />}{data.status}</div></header>
    <section aria-label="Latest evaluator metrics" className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Latest status", latest?.status ?? "No runs"], ["Duration", latest?.durationMs == null ? "Unavailable" : `${latest.durationMs} ms`], ["Watches evaluated", latest?.watchesEvaluated ?? 0], ["Notifications created", latest?.notificationsCreated ?? 0], ["Skipped watches", latest?.watchesSkipped ?? 0], ["Errors", latest?.errors ?? 0]].map(([label, value]) => <div key={label} className="rounded-lg border border-[#eadfdf] bg-white p-5"><p className="text-sm text-[#6f626b]">{label}</p><p className="mt-3 break-words text-2xl font-bold tabular-nums">{value}</p></div>)}</section>
    <section className="mt-7 border-y border-[#eadfdf] py-5"><div className="flex items-center gap-2"><Clock3 size={19} /><h2 className="font-bold">Last successful run</h2></div><p className="mt-2 text-sm">{data.lastSuccessful?.completedAt ? `${data.lastSuccessful.completedAt.toISOString().replace("T", " ").slice(0, 19)} UTC` : "No successful run recorded."}</p>{data.stale && <p className="mt-2 text-sm font-semibold text-amber-800">No successful evaluation has completed within the expected 60-minute interval.</p>}{data.repeatedFailures && <p className="mt-2 text-sm font-semibold text-amber-800">At least two of the latest three runs failed.</p>}</section>
    <section className="mt-7"><h2 className="text-lg font-bold">Recent run history</h2>{data.runs.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-y border-[#eadfdf] text-xs text-[#6f626b]"><th className="p-3">Started</th><th className="p-3">Source</th><th className="p-3">Status</th><th className="p-3 text-right">Evaluated</th><th className="p-3 text-right">Created</th><th className="p-3 text-right">Skipped</th><th className="p-3 text-right">Errors</th><th className="p-3 text-right">Duration</th></tr></thead><tbody>{data.runs.map(run => <tr key={run.id} className="border-b border-[#eadfdf]"><td className="p-3 whitespace-nowrap">{run.startedAt.toISOString().replace("T", " ").slice(0, 19)} UTC</td><td className="p-3">{run.source}</td><td className="p-3 font-semibold">{run.status}</td><td className="p-3 text-right">{run.watchesEvaluated}</td><td className="p-3 text-right">{run.notificationsCreated}</td><td className="p-3 text-right">{run.watchesSkipped}</td><td className="p-3 text-right">{run.errors}</td><td className="p-3 text-right">{run.durationMs == null ? "-" : `${run.durationMs} ms`}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-[#6f626b]">No evaluator runs recorded yet.</p>}</section></>;
}
