import Link from "next/link";
import { Bell, BellOff, Search, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { savedSearchUrl, type SavedSearchCriteria } from "@/lib/saved-searches";
import { deleteSavedSearchAction, renameSavedSearchAction, setSavedSearchEnabledAction } from "@/app/actions/saved-searches";
import { listedDate } from "@/lib/market";

export default async function SavedSearchesPage() {
  const user = await requireUser();
  const searches = await prisma.savedSearch.findMany({ where: { userId: user.id }, orderBy: [{ createdAt: "desc" }, { id: "desc" }] });
  return <AppShell><header><p className="text-xs font-bold uppercase text-[#47715f]">Discovery alerts</p><h1 className="mt-2 text-3xl font-bold">Saved searches</h1><p className="mt-3 text-sm text-[#6f626b]">Open your exact filters and control notifications for newly matching active listings.</p></header>
    {searches.length ? <div className="mt-7 divide-y divide-[#eadfdf] border-y border-[#eadfdf]">{searches.map(search => {
      const criteria: SavedSearchCriteria = { q: search.q, category: search.category ?? "", commodity: search.commodity ?? "", variety: search.variety ?? "", grade: search.grade ?? "", country: search.country ?? "", location: search.location ?? "", unit: search.unit ?? "", minPrice: search.minPrice?.toString() ?? "", maxPrice: search.maxPrice?.toString() ?? "", sort: search.sort as SavedSearchCriteria["sort"] };
      return <article key={search.id} className="py-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-lg font-bold">{search.name}</h2><span className={`text-xs font-bold ${search.enabled ? "text-[#47715f]" : "text-[#8b7d85]"}`}>{search.enabled ? "Enabled" : "Disabled"}</span></div><p className="mt-2 text-sm text-[#6f626b]">{search.q ? `Search: ${search.q}` : "Filtered marketplace search"}{search.lastEvaluatedAt ? ` · Checked ${listedDate(search.lastEvaluatedAt)}` : ""}</p><Link href={savedSearchUrl(criteria)} className="mt-3 inline-flex min-h-10 items-center gap-2 text-sm font-bold text-[#47715f] underline"><Search size={17} />Open marketplace results</Link></div><div className="flex flex-wrap gap-2"><form action={setSavedSearchEnabledAction}><input type="hidden" name="id" value={search.id} /><input type="hidden" name="enabled" value={String(!search.enabled)} /><button className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#d9cccc] bg-white px-3 text-sm font-bold">{search.enabled ? <BellOff size={17} /> : <Bell size={17} />}{search.enabled ? "Disable" : "Enable"}</button></form><form action={deleteSavedSearchAction}><input type="hidden" name="id" value={search.id} /><button aria-label={`Delete ${search.name}`} title="Delete saved search" className="grid size-11 place-items-center rounded-lg border border-[#d9cccc] bg-white text-[#9d334b]"><Trash2 size={18} /></button></form></div></div><form action={renameSavedSearchAction} className="mt-4 flex max-w-xl gap-2"><input type="hidden" name="id" value={search.id} /><label className="min-w-0 flex-1"><span className="sr-only">Rename {search.name}</span><input name="name" defaultValue={search.name} maxLength={80} required className="min-h-11 w-full rounded-lg border border-[#d9cccc] bg-white px-3 text-sm" /></label><button className="min-h-11 rounded-lg bg-[#20141d] px-4 text-sm font-bold text-white">Rename</button></form></article>;
    })}</div> : <section className="mt-8 border-y border-dashed border-[#d9cccc] py-14"><Search size={30} className="text-[#9d334b]" /><h2 className="mt-4 text-xl font-bold">No saved searches yet.</h2><p className="mt-2 text-sm text-[#6f626b]">Apply a useful search or filter in the marketplace, then save it.</p><Link href="/market" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-[#20141d] px-5 text-sm font-bold text-white">Browse marketplace</Link></section>}
  </AppShell>;
}
