import Link from "next/link";
import { Handshake } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DealControls } from "@/components/deal-controls";
import { DealReview } from "@/components/deal-review";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Avatar } from "@/components/avatar";
import { canReview, dealsAwaitingConfirmationWhere } from "@/lib/deals";
import { EmptyState } from "@/components/ui";

export default async function DealsPage({ searchParams }: { searchParams: Promise<{ review?: string; message?: string; focus?: string }> }) {
  const [user, params] = await Promise.all([requireUser(), searchParams]);
  const waitingOnly = params.focus === "waiting";
  const deals = await prisma.deal.findMany({ where: waitingOnly ? dealsAwaitingConfirmationWhere(user.id) : { OR: [{ buyerId: user.id }, { sellerId: user.id }] }, include: { product: { select: { id: true, item: true, status: true, price: true, quantity: true, remainingQuantity: true, unit: true } }, buyer: { select: { name: true, imageUrl: true } }, seller: { select: { name: true, imageUrl: true } }, reviews: { where: { reviewerId: user.id }, select: { status: true, rating: true, comment: true }, take: 1 } }, orderBy: { createdAt: "desc" } });
  const eligibleReviewIds = new Set((await Promise.all(deals.map(async deal => ({ id: deal.id, eligible: await canReview(user.id, deal.id, deal.buyerId === user.id ? deal.sellerId : deal.buyerId) })))).filter(item => item.eligible).map(item => item.id));
  return <AppShell><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{waitingOnly ? "Deals waiting for you" : "Deals"}</h1><p className="mt-2 text-sm text-[#6f626b]">Private agreed marketplace terms. Completion does not confirm payment.</p></div>{waitingOnly && <Link href="/deals" className="inline-flex min-h-11 items-center text-sm font-bold underline">View all deals</Link>}</div>{params.review === "submitted" && <p role="status" className="mt-5 rounded-lg border border-green-200 bg-green-50 p-3 text-sm font-semibold text-green-800">Review submitted for moderation.</p>}{params.review === "error" && <p role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{params.message ?? "Review submission failed."}</p>}
    {deals.length ? <div className="mt-6 divide-y border-y border-[#eadfdf]">{deals.map(deal => { const other = deal.buyerId === user.id ? deal.seller : deal.buyer; return <article id={`deal-${deal.id}`} key={deal.id} className="scroll-mt-24 py-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Avatar name={other.name} imageUrl={other.imageUrl} /><div><Link href={`/messages/${deal.conversationId}#deal-${deal.id}`} className="font-bold underline">{deal.product.item}</Link><p className="mt-1 text-sm text-[#6f626b]">With {other.name} · Listing {deal.product.status.toLowerCase()}</p></div></div>{deal.completedAt && <time className="text-xs text-[#6f626b]" dateTime={deal.completedAt.toISOString()}>Completed {deal.completedAt.toISOString().slice(0, 10)}</time>}</div><div className="mt-3"><DealControls conversationId={deal.conversationId} viewerId={user.id} sellerId={deal.sellerId} sellerName={deal.seller.name} listingName={deal.product.item} blocked={false} productActive={deal.product.status === "ACTIVE"} available={deal.product.remainingQuantity ?? deal.product.quantity} unit={deal.product.unit} askingPrice={deal.product.price} askingQuantity={deal.product.quantity} deal={deal} /></div>{deal.status === "COMPLETED" && <nav className="mt-3 flex flex-wrap gap-4 text-sm font-bold"><Link href={`/market/${deal.product.id}`} className="min-h-11 content-center underline">View listing</Link><Link href={`/messages/${deal.conversationId}`} className="min-h-11 content-center underline">Continue conversation</Link></nav>}<DealReview dealId={deal.id} eligible={eligibleReviewIds.has(deal.id)} review={deal.reviews[0]} /></article>; })}</div> : <div className="mt-8"><EmptyState icon={<Handshake size={28} />} title={waitingOnly ? "Nothing is waiting for you" : "No deals yet"} description={waitingOnly ? "You are caught up. New confirmations will appear here." : "Deals begin in a conversation after you and a seller agree on terms."} href={waitingOnly ? "/deals" : "/market"} action={waitingOnly ? "View deal history" : "Browse marketplace"} /></div>}
  </AppShell>;
}
