import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { prisma } from "@/lib/prisma";
import { closeSafetyReportAction } from "@/app/actions/safety-reports";

const statuses = ["OPEN", "RESOLVED", "DISMISSED"] as const;
const targets = ["USER", "LISTING", "MESSAGE"] as const;
const reasons = ["HARASSMENT", "SPAM_OR_SCAM", "MISLEADING", "PERSONAL_INFORMATION", "PROHIBITED_OR_UNSAFE", "IMPERSONATION", "OTHER"] as const;

export default async function AdminReportsPage({ searchParams }: { searchParams: Promise<{ status?: string; target?: string; reason?: string; order?: string; q?: string; page?: string }> }) {
  await requireAdmin(); const query = await searchParams;
  const status = statuses.includes(query.status as typeof statuses[number]) ? query.status as typeof statuses[number] : "OPEN";
  const target = targets.includes(query.target as typeof targets[number]) ? query.target as typeof targets[number] : undefined;
  const reason = reasons.includes(query.reason as typeof reasons[number]) ? query.reason as typeof reasons[number] : undefined;
  const q = String(query.q ?? "").trim().slice(0, 100); const order = query.order === "oldest" ? "asc" : "desc";
  const page = Math.max(1, Number.parseInt(query.page ?? "1", 10) || 1); const pageSize = 25;
  const where = { status, ...(target ? { targetType: target } : {}), ...(reason ? { reason } : {}), ...(q ? { OR: [{ targetUserName: { contains: q, mode: "insensitive" as const } }, { listingName: { contains: q, mode: "insensitive" as const } }, { messageAuthorName: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const [reports, total] = await Promise.all([prisma.safetyReport.findMany({ where, include: { reporter: { select: { name: true } }, targetUser: { select: { name: true } }, listing: { select: { item: true, status: true } } }, orderBy: [{ createdAt: order }, { id: order }], skip: (page - 1) * pageSize, take: pageSize }), prisma.safetyReport.count({ where })]);
  const pages = Math.max(1, Math.ceil(total / pageSize)); const pageHref = (value: number) => `?${new URLSearchParams({ status, ...(target ? { target } : {}), ...(reason ? { reason } : {}), ...(q ? { q } : {}), order: order === "asc" ? "oldest" : "newest", page: String(value) })}`;
  return <><header><p className="text-xs font-bold uppercase text-[#996066]">Marketplace safety</p><h1 className="mt-2 text-3xl font-bold">Safety reports</h1><p className="mt-3 text-sm text-[#6f626b]">Private reports do not change accounts or listings until an administrator explicitly acts.</p></header>
    <form className="mt-6 grid gap-3 border-y border-[#eadfdf] py-4 sm:grid-cols-2 xl:grid-cols-5"><label className="grid gap-1 text-xs font-bold">Status<select name="status" defaultValue={status} className="min-h-10 rounded border px-2">{statuses.map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Target<select name="target" defaultValue={target ?? ""} className="min-h-10 rounded border px-2"><option value="">All</option>{targets.map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Reason<select name="reason" defaultValue={reason ?? ""} className="min-h-10 rounded border px-2"><option value="">All</option>{reasons.map(value => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Search<input name="q" defaultValue={q} className="min-h-10 rounded border px-2" /></label><label className="grid gap-1 text-xs font-bold">Order<select name="order" defaultValue={order === "asc" ? "oldest" : "newest"} className="min-h-10 rounded border px-2"><option value="newest">Newest</option><option value="oldest">Oldest</option></select></label><button className="min-h-10 w-fit rounded bg-[#20141d] px-4 text-sm font-bold text-white">Apply filters</button></form>
    <div className="mt-6 divide-y border-y border-[#eadfdf]">{reports.map(report => <article key={report.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{report.targetType} · {report.reason.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-[#6f626b]">Target: {report.targetUser?.name ?? report.targetUserName ?? report.listing?.item ?? report.listingName ?? report.messageAuthorName ?? "Deleted target"}</p><p className="mt-1 text-xs text-[#6f626b]">Reported by {report.reporter.name} · {report.createdAt.toISOString()}</p></div><span className="text-xs font-bold">{report.status}</span></div>{report.note && <p className="mt-3 whitespace-pre-wrap break-words text-sm">Reporter note: {report.note}</p>}{report.messageBodySnapshot && <blockquote className="mt-3 border-l-2 border-[#d9cccc] pl-3 text-sm text-[#6f626b]">Message snapshot: {report.messageBodySnapshot}</blockquote>}{report.status === "OPEN" && <form action={closeSafetyReportAction} className="mt-4 flex flex-wrap items-end gap-2"><input type="hidden" name="reportId" value={report.id} /><label className="grid min-w-[220px] flex-1 gap-1 text-xs font-bold">Private moderator note<input name="moderatorNote" maxLength={500} className="min-h-10 rounded border px-2 font-normal" /></label>{report.targetType === "LISTING" && report.listingId && <label className="flex min-h-10 items-center gap-2 text-xs font-bold"><input type="checkbox" name="deactivateListing" value="1" />Mark listing inactive</label>}<button name="status" value="RESOLVED" className="min-h-10 rounded bg-[#20141d] px-3 text-sm font-bold text-white">Resolve</button><button name="status" value="DISMISSED" className="min-h-10 rounded border px-3 text-sm font-bold">Dismiss</button></form>}</article>)}</div>{!reports.length && <p className="py-10 text-sm text-[#6f626b]">No safety reports match these filters.</p>}{pages > 1 && <nav aria-label="Safety report pagination" className="mt-5 flex justify-between text-sm"><span>Page {page} of {pages}</span><span className="flex gap-4">{page > 1 && <Link href={pageHref(page - 1)} className="underline">Previous</Link>}{page < pages && <Link href={pageHref(page + 1)} className="underline">Next</Link>}</span></nav>}
  </>;
}
