import assert from "node:assert/strict";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

process.loadEnvFile();
const base = process.env.TEST_APP_URL || "http://localhost:3101";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL, max: 1, idleTimeoutMillis: 1000 }) });
const manifest = JSON.parse(readFileSync(new URL("../.next/server/server-reference-manifest.json", import.meta.url), "utf8"));
const emails = [];
async function action(path, name, values, cookie = "") {
  const entry = Object.entries(manifest.node).find(([, value]) => value.exportedName === name);
  assert.ok(entry, `Missing action ${name}`);
  const form = new FormData();
  form.set("$ACTION_ID_" + entry[0], "");
  for (const [key, value] of Object.entries(values)) form.set(key, value);
  return fetch(base + path, { method: "POST", headers: { Origin: base, Cookie: cookie }, body: form, redirect: "manual" });
}
async function account(name) {
  const email = `http-test-${randomUUID()}@example.invalid`;
  emails.push(email);
  const password = "Sauti-test-password-123";
  const response = await action("/register", "registerAction", { name, email, password, confirmPassword: password, phone: randomUUID().replaceAll("-", "").slice(0, 20), country: "KE", location: "Nairobi" });
  assert.equal(response.status, 303);
  assert.ok(response.headers.get("location").startsWith("/login?registered=1"), response.headers.get("location"));
  const user = await prisma.user.findUniqueOrThrow({ where: { email } });
  assert.ok(await bcrypt.compare(password, user.passwordHash));
  const login = await action("/login", "loginAction", { email, password });
  assert.equal(login.headers.get("location"), "/dashboard");
  const cookie = login.headers.get("set-cookie").split(";")[0];
  assert.match(login.headers.get("set-cookie"), /HttpOnly/i);
  return { user, cookie };
}
try {
  assert.equal((await fetch(base + "/api/chat?country=KE")).status, 401);
  assert.equal((await fetch(base + "/api/uploads/product", { method: "POST", headers: { Origin: base }, body: new FormData() })).status, 401);
  assert.equal((await fetch(base + "/messages", { redirect: "manual" })).status, 307);
  assert.equal((await fetch(base + "/admin/dashboard", { redirect: "manual" })).status, 307);
  const invalid = await action("/register", "registerAction", { country: "KE" });
  const invalidPage = await (await fetch(base + invalid.headers.get("location"))).text();
  assert.ok(invalidPage.includes('role="alert"'), "Registration must display server validation errors");
  const seller = await account("HTTP Seller");
  const duplicate = await action("/register", "registerAction", { name: "Duplicate Account", email: seller.user.email, password: "Sauti-test-password-123", confirmPassword: "Sauti-test-password-123", phone: "test-duplicate-phone", country: "KE", location: "Nairobi" });
  const duplicatePage = await (await fetch(base + duplicate.headers.get("location"))).text();
  assert.ok(duplicatePage.includes("An account with that email already exists."));
  const wrongPassword = await action("/login", "loginAction", { email: seller.user.email, password: "wrong-password" });
  assert.ok(wrongPassword.headers.get("location").includes("Invalid%20email%20or%20password"));
  const wrongPasswordPage = await (await fetch(base + wrongPassword.headers.get("location"))).text();
  assert.ok(wrongPasswordPage.includes("Invalid email or password."));
  assert.ok(wrongPasswordPage.includes(seller.user.email), "Retain login email after an error");
  const buyer = await account("HTTP Buyer");
  const outsider = await account("HTTP Outsider");
  for (const route of ["/admin", "/admin/dashboard", "/admin/search?q=HTTP"]) {
    assert.equal((await fetch(base + route, { headers: { Cookie: outsider.cookie }, redirect: "manual" })).status, 404);
  }
  const created = await action("/listings/new", "createListingAction", { item: "HTTP test beans", category: "Beans", price: "12.50", quantity: "1", unit: "KG", description: "Fresh beans for integration testing", location: "Nairobi", country: "KE" }, seller.cookie);
  assert.equal(created.headers.get("location"), "/listings?created=1");
  const product = await prisma.product.findFirstOrThrow({ where: { ownerId: seller.user.id } });
  assert.equal(product.imageUrl, null);
  const photoListing = { item: "HTTP photo flowers", category: "Other", price: "8", quantity: "1", unit: "ITEM", description: "Photo validation test flowers", location: "Nairobi", country: "KE" };
  for (const imageUrl of ["http://localhost/photo.jpg", "https://example.com/photo.jpg", "https://res.cloudinary.com/demo/image/fetch/https://localhost/a.jpg", "https://images.unsplash.com/photo-test.svg"]) {
    const rejected = await action("/listings/new", "createListingAction", { ...photoListing, imageUrl }, seller.cookie);
    assert.ok(rejected.headers.get("location").includes("error="), "Reject unsupported image URL");
  }
  assert.equal(await prisma.product.count({ where: { ownerId: seller.user.id } }), 1);
  const imageUrl = "https://res.cloudinary.com/demo/image/upload/sample.jpg";
  const photoCreated = await action("/listings/new", "createListingAction", { ...photoListing, imageUrl, ownerId: buyer.user.id }, seller.cookie);
  assert.ok(photoCreated.headers.get("location").includes("error="), "Manual image metadata must not be accepted");
  const photoProduct = await prisma.product.create({ data: { ...photoListing, price: 8, imageUrl, ownerId: seller.user.id } });
  assert.equal(photoProduct.imageUrl, imageUrl);
  const detail = await (await fetch(base + "/market/" + photoProduct.id)).text();
  const publicSeller = await (await fetch(base + "/sellers/" + seller.user.id)).text();
  assert.ok(detail.includes(photoListing.description));
  assert.ok(detail.includes("/sellers/" + seller.user.id));
  assert.ok(publicSeller.includes(photoListing.item));
  for (const html of [detail, publicSeller]) {
    for (const secret of [seller.user.email, seller.user.phone, seller.user.passwordHash]) assert.ok(!html.includes(secret), "Public pages must exclude private seller fields");
  }
  assert.equal((await fetch(base + `/listings/${product.id}/edit`, { headers: { Cookie: buyer.cookie } })).status, 404);
  assert.equal((await fetch(base + `/listings/${product.id}/edit`, { headers: { Cookie: seller.cookie } })).status, 200);
  const paginationTag = randomUUID();
  await prisma.product.createMany({ data: Array.from({ length: 13 }, (_, index) => ({ ...photoListing, item: `Page fixture ${index}`, description: paginationTag, price: 8, ownerId: seller.user.id })) });
  const firstPage = await (await fetch(base + `/market?q=${paginationTag}&country=KE`)).text();
  const secondPage = await (await fetch(base + `/market?q=${paginationTag}&country=KE&page=2`)).text();
  const listingLinks = html => new Set([...html.matchAll(/href="\/market\/([^"?]+)/g)].map(match => match[1]).filter(id => id !== "insights"));
  assert.equal(listingLinks(firstPage).size, 12);
  assert.equal(listingLinks(secondPage).size, 1);
  assert.ok(firstPage.includes("country=KE&amp;page=2"));
  await prisma.product.deleteMany({ where: { ownerId: seller.user.id, description: paginationTag } });
  assert.ok((await (await fetch(base + "/market?country=KE")).text()).includes(product.item));
  assert.ok(!(await (await fetch(base + "/market?country=UG")).text()).includes(product.item));
  const contacted = await action("/market", "contactSeller", { productId: product.id }, buyer.cookie);
  const path = contacted.headers.get("location");
  assert.match(path, /^\/messages\//);
  const conversationId = path.split("/").pop();
  assert.equal((await fetch(base + path, { headers: { Cookie: buyer.cookie } })).status, 200);
  assert.equal((await fetch(base + path, { headers: { Cookie: outsider.cookie } })).status, 404);
  const send = (cookie, body, origin = base) => fetch(base + "/api/chat", { method: "POST", headers: { Cookie: cookie, Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify(body) });
  assert.equal((await send(buyer.cookie, { conversationId, body: "Available?" }, "https://other.invalid")).status, 403);
  assert.equal((await send(buyer.cookie, { conversationId, body: "Available?" })).status, 200);
  const received = await (await fetch(base + "/api/chat?conversationId=" + conversationId, { headers: { Cookie: seller.cookie } })).json();
  assert.equal(received.messages[0].body, "Available?");
  assert.equal((await fetch(base + "/api/chat?conversationId=" + conversationId, { headers: { Cookie: outsider.cookie } })).status, 404);
  assert.equal((await send(seller.cookie, { country: "KE", body: "Country room HTTP test" })).status, 200);
  const room = await (await fetch(base + "/api/chat?country=KE", { headers: { Cookie: buyer.cookie } })).json();
  assert.ok(room.messages.some(m => m.body === "Country room HTTP test"));
  const report = await action(path, "reportMessage", { messageId: received.messages[0].id, reason: "Integration test report" }, seller.cookie);
  assert.equal(report.headers.get("location"), "/messages?reported=1");
  const savedReport = await prisma.messageReport.findFirstOrThrow({ where: { reporterId: seller.user.id } });
  await action("/messages/moderation", "moderateReport", { reportId: savedReport.id, hide: "1" }, outsider.cookie);
  assert.equal((await prisma.message.findUniqueOrThrow({ where: { id: savedReport.messageId } })).hidden, false);
  await prisma.user.update({ where: { id: seller.user.id }, data: { role: "ADMIN" } });
  const overview = await fetch(base + "/admin/dashboard?days=7", { headers: { Cookie: seller.cookie } });
  assert.equal(overview.status, 200);
  const overviewHtml = await overview.text();
  assert.ok(overviewHtml.includes("Marketplace overview"));
  assert.ok(overviewHtml.includes("Not available"));
  assert.ok(!overviewHtml.includes(seller.user.passwordHash));
  const adminSearch = await fetch(base + "/admin/search?type=users&q=" + encodeURIComponent(buyer.user.email), { headers: { Cookie: seller.cookie } });
  assert.equal(adminSearch.status, 200);
  assert.ok((await adminSearch.text()).includes(buyer.user.email));
  const reportRecords = await (await fetch(base + "/admin/search?type=reports", { headers: { Cookie: seller.cookie } })).text();
  assert.ok(reportRecords.includes(savedReport.id));
  assert.ok(!reportRecords.includes("Available?"), "Admin record search must not expose private messages");
  const noMatches = await (await fetch(base + "/admin/search?q=" + randomUUID(), { headers: { Cookie: seller.cookie } })).text();
  assert.ok(noMatches.includes("No matching records."));
  const invalidQuery = await fetch(base + "/admin/search?page=-1&type=unknown", { headers: { Cookie: seller.cookie } });
  assert.equal(invalidQuery.status, 200);
  await prisma.user.update({ where: { id: seller.user.id }, data: { role: "USER" } });
  assert.equal((await fetch(base + "/admin/dashboard", { headers: { Cookie: seller.cookie } })).status, 404);
  await prisma.user.update({ where: { id: seller.user.id }, data: { role: "ADMIN" } });
  await action("/messages/moderation", "moderateReport", { reportId: savedReport.id, hide: "1" }, seller.cookie);
  assert.equal((await prisma.message.findUniqueOrThrow({ where: { id: savedReport.messageId } })).hidden, true);
  const token = randomBytes(32).toString("hex");
  await prisma.passwordReset.create({ data: { userId: outsider.user.id, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60000) } });
  const reset = await action("/reset-password", "resetPassword", { token, password: "Updated-password-123", confirmPassword: "Updated-password-123" });
  assert.equal(reset.headers.get("location"), "/login?reset=1");
  assert.equal((await fetch(base + "/api/chat?country=KE", { headers: { Cookie: outsider.cookie } })).status, 401);
  const relogin = await action("/login", "loginAction", { email: outsider.user.email, password: "Updated-password-123" });
  assert.equal(relogin.headers.get("location"), "/dashboard");
  if (!process.env.RESEND_API_KEY || !process.env.EMAIL_FROM || !process.env.APP_URL) {
    const unavailable = await action("/forgot-password", "requestReset", { email: buyer.user.email });
    assert.match(unavailable.headers.get("location"), /unavailable/);
  }
  const deletion = { type: "listings", id: product.id, reason: "Automated integration test deletion", confirmation: "DELETE" };
  const deniedDeletion = await action("/admin/delete", "adminDeleteAction", deletion, buyer.cookie);
  assert.equal(deniedDeletion.status, 404);
  assert.ok(await prisma.product.findUnique({ where: { id: product.id } }));
  const unconfirmed = await action("/admin/delete", "adminDeleteAction", { ...deletion, confirmation: "" }, seller.cookie);
  assert.ok(unconfirmed.headers.get("location").includes("error="));
  assert.ok(await prisma.product.findUnique({ where: { id: product.id } }));
  const selfDelete = await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "users", id: seller.user.id }, seller.cookie);
  assert.ok(selfDelete.headers.get("location").includes("error="));
  await prisma.user.update({ where: { id: outsider.user.id }, data: { role: "ADMIN" } });
  const otherAdmin = await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "users", id: outsider.user.id }, seller.cookie);
  assert.ok(otherAdmin.headers.get("location").includes("error="));
  await prisma.user.update({ where: { id: outsider.user.id }, data: { role: "USER" } });
  const privateMessage = await prisma.message.create({ data: { authorId: buyer.user.id, conversationId, body: "Unreported private content" } });
  const privateDelete = await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "messages", id: privateMessage.id }, seller.cookie);
  assert.ok(privateDelete.headers.get("location").includes("error="));
  assert.ok(await prisma.message.findUnique({ where: { id: privateMessage.id } }));
  const deletedMessage = await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "messages", id: savedReport.messageId }, seller.cookie);
  assert.equal(deletedMessage.headers.get("location"), "/admin/audit-logs?deleted=1");
  assert.equal(await prisma.message.findUnique({ where: { id: savedReport.messageId } }), null);
  const publicMessage = await prisma.message.findFirstOrThrow({ where: { authorId: seller.user.id, country: "KE" } });
  await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "messages", id: publicMessage.id }, seller.cookie);
  assert.equal(await prisma.message.findUnique({ where: { id: publicMessage.id } }), null);
  const deletedProduct = await action("/admin/delete", "adminDeleteAction", deletion, seller.cookie);
  assert.equal(deletedProduct.headers.get("location"), "/admin/audit-logs?deleted=1");
  assert.equal(await prisma.product.findUnique({ where: { id: product.id } }), null);
  assert.equal((await prisma.conversation.findUniqueOrThrow({ where: { id: conversationId } })).productId, null);
  const deletedUser = await action("/admin/delete", "adminDeleteAction", { ...deletion, type: "users", id: buyer.user.id }, seller.cookie);
  assert.equal(deletedUser.headers.get("location"), "/admin/audit-logs?deleted=1");
  assert.equal(await prisma.user.findUnique({ where: { id: buyer.user.id } }), null);
  assert.equal(await prisma.conversation.findUnique({ where: { id: conversationId } }), null);
  assert.equal((await fetch(base + "/api/chat?country=KE", { headers: { Cookie: buyer.cookie } })).status, 401);
  assert.equal(await prisma.auditLog.count({ where: { adminId: seller.user.id } }), 4);
  const logout = await action("/dashboard", "logoutAction", {}, buyer.cookie);
  assert.equal(logout.headers.get("location"), "/login");
  assert.match(logout.headers.get("set-cookie"), /sauti_session=;/);
  console.log("PASS HTTP: authentication, listing images and validation, public seller privacy, pagination, ownership, chat, admin authorization, deletion confirmation, protected admins, message privacy, deletion cascades, session invalidation and atomic audit records.");
} finally {
  await prisma.user.deleteMany({ where: { email: { in: emails } } });
  await prisma.$disconnect();
}
